<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('lift') ?>">
<!--                <img src="--><?php //echo $this->basePath('img/zf2-logo.png') ?><!--" alt="Zend Framework 2"/>&nbsp;-->
                <?php echo $this->translate('LIFT!') ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach ($this->container as $page):?>
                    <?php if($this->navigation()->accept($page)): ?>
                    <li class="<?=$page->isActive(true) ? 'active' : ''?>">
                        <a href="<?=$page->getHref()?>">
                            <?=$this->escapeHtml($page->getLabel())?>
                        </a>
                    </li>
                    <?php endif;?>
                <?php endforeach;?>
            </ul>
            <?=$this->liftAuthElement($this->url('lift/auth', ['action' => 'login']), $this->url('lift/auth', ['action' => 'logout']))?>
        </div>
    </div>
</nav>
