<div class="row">
    <div class="col">
        <form class="form-inline" method="get">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search" name="search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col">
        <?=$this->table?>
    </div>
</div>
<div class="row">
    <div class="col">
        <?=$this->footer?>
    </div>
</div>


