<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->first), array(), true); ?>">
                First
            </a> |
        <?php else: ?>
            <span class="disabled">First</span> |
        <?php endif; ?>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->previous), array(), true); ?>">
                &lt; Previous
            </a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url($this->route, array('page' => $page), array(), true); ?>">
                    <?php echo $page; ?>
                </a> |
            <?php else: ?>
                <?php echo $page; ?> |
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->next), array(), true); ?>">
                Next &gt;
            </a>
        <?php else: ?>
            <span class="disabled">Next &gt;</span>
        <?php endif; ?>

        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url($this->route, array('page' => $this->last), array(), true); ?>">
                Last
            </a>
        <?php else: ?>
            <span class="disabled">Last</span>
        <?php endif; ?>
    </div>
<?php endif; ?>