<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/application.config.old
 */
return array(
    'modules' => array(
        'DoctrineModule',
        'DoctrineORMModule',
        'Application',
        'Lift',
        'ZendDeveloperTools',
        'Zend\\Navigation',
        'GmM2M',
        'ZF\\Apigility',
        'ZF\\Apigility\\Admin',
        'ZF\\Apigility\\Provider',
        'Phpro\DoctrineHydrationModule',
        'ZF\Apigility\Doctrine\Admin',
        'ZF\Apigility\Doctrine\Server',
        'ZF\\ApiProblem',
        'ZF\\MvcAuth',
        'ZF\\OAuth2',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'ZF\\OAuth2\\Doctrine',
        'ZF\\OAuth2\\Doctrine\\Console',
        'ZF\\OAuth2\\Client',
        'ZF\\Apigility\\Documentation',
        'ZF\\Apigility\\Documentation\\ApiBlueprint',
        'ZF\\Apigility\\Documentation\\Swagger',
        'Tasks',
        'Sample',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './module02',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
        ),
    ),
);
