<?php
    $this->form->prepare();
?>

<button onclick="return add_category()">Add</button>

<?=$this->form($this->form);?>

<?php $this->inlineScript()->captureStart()?>

    function add_category() {
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('form > fieldset').append(template);
        $('form > fieldset > fieldset > button').on('click', function(){
            $(this).parent().remove();
        });
        return false;
    }

    $('.remove-btn').on('click', function(){
        $(this).parent().remove();
    });

<?php $this->inlineScript()->captureEnd()?>
