<table class="table">
    <thead>
    <tr>
        <th><?=$this->translate('FROM')?></th>
        <th><?=$this->translate('TO')?></th>
        <th><?=$this->translate('UPDATED')?></th>
        <th>ACTIONS</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->items as $item):?>
        <tr>
            <td><?=$this->escapeHtml($item['fromLocation'])?></td>
            <td><?=$this->escapeHtml($item['toLocation'])?></td>
            <td><?=$this->dateFormat($item['updatedAt'], IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM)?></td>
            <td>
                <a href="<?=$this->url('lift/my_offer/update', ['id' => $item['id']])?>">CHANGE</a> |
                <a href="<?=$this->url('lift/my_offer/delete', ['id' => $item['id']])?>">WITHDRAW</a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

