<!-- <div class="row">
    <div class="col">
        <form class="form-horizontal" method="post">
            <div class="form-group">
                <label class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Username" name="user_name" value="<?=$this->values['user_name']?>">
                    <?=(array_key_exists('user_name', $this->errors)) ? "<div>" .implode('<br>', $this->errors['user_name']). "</div>" : '';?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">First Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="First Name" name="first_name" value="<?=$this->values['first_name']?>">
                    <?=(array_key_exists('first_name', $this->errors)) ? "<div>" .implode('<br>', $this->errors['first_name']). "</div>" : '';?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Last Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" placeholder="Password" name="password">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Confirm password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" placeholder="Password" name="confirm_password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Register</button>
                </div>
            </div>
        </form>
    </div>
</div> -->

<?=$this->form($this->user_registration_form);?>
