<?php
$this->user_registration_form->prepare();
$userRegistrationFs = $this->user_registration_form->get('user_registration');
$userFs = $userRegistrationFs->get('user');
?>

<div class="row">
    <div class="col">
        <?=$this->form()->openTag($this->user_registration_form)?>
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    <?=$this->formLabel($userFs->get('user_name'))?>
                </label>
                <div class="col-sm-10">
                    <?=$this->formText($userFs->get('user_name')->setAttribute('class', 'form-control'))?>
                    <?=$this->formElementErrors($userFs->get('user_name'))?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    <?=$this->formLabel($userFs->get('first_name'))?>
                </label>
                <div class="col-sm-10">
                    <?=$this->formText($userFs->get('first_name')->setAttribute('class', 'form-control'))?>
                    <?=$this->formElementErrors($userFs->get('first_name'))?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"><?=$this->formLabel($userFs->get('last_name'))?></label>
                <div class="col-sm-10">
                    <?=$this->formText($userFs->get('last_name')->setAttribute('class', 'form-control'))?>
                    <?=$this->formElementErrors($userFs->get('last_name'))?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"><?=$this->formLabel($userFs->get('password'))?></label>
                <div class="col-sm-10">
                    <?=$this->formPassword($userFs->get('password')->setAttribute('class', 'form-control'))?>
                    <?=$this->formElementErrors($userFs->get('password'))?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"><?=$this->formLabel($userFs->get('password_confirm'))?></label>
                <div class="col-sm-10">
                    <?=$this->formPassword($userFs->get('password_confirm')->setAttribute('class', 'form-control'))?>
                    <?=$this->formElementErrors($userFs->get('password_confirm'))?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"><?=$this->formLabel($userRegistrationFs->get('found_at'))?></label>
                <div class="col-sm-10">
                    <?=$this->formText($userRegistrationFs->get('found_at')->setAttribute('class', 'form-control'))?>
                    <?=$this->formElementErrors($userRegistrationFs->get('found_at'))?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <?=$this->formSubmit($this->user_registration_form->get('submit'))?>
                </div>
            </div>
        <?=$this->form()->closeTag()?>
    </div>
</div>
